name: risk-sim-figures
channels:
  - defaults
  - conda-forge
dependencies:
  - pip==20.0.2
  - plotly-orca==1.3.1
  - imagemagick
  - python=3.6
  - pip:
      - git+git://github.com/tidepool-org/data-science-models
      - -r file:requirements.txt
